### ISSUE TITLE
failed to create macvlan: invalid argument

### ISSUE THREAD

**Issue by mupeifeiyi** [Mellanox/network-operator#1017]
kubernetes version: 1.21.14
network-operator: 23.10
The operator configuration is as follows, and the others are default
```
deployCR: true
rdmaSharedDevicePlugin:
  deploy: true
  image: k8s-rdma-shared-dev-plugin
  repository: ghcr.io/mellanox
  version: sha-fe7f371c7e1b8315bf900f71cd25cfc1251dc775
  useCdi: false
  resources:
    - name: mlx5_1
      vendors: [15b3]
      rdmaHcaMax: 63
      ifNames: [ib1]
    - name: mlx5_2
      vendors: [15b3]
      rdmaHcaMax: 63
      ifNames: [ib2]
    - name: mlx5_3
      vendors: [15b3]
      rdmaHcaMax: 63
      ifNames: [ib3]
    - name: mlx5_4
      vendors: [15b3]
      rdmaHcaMax: 63
      ifNames: [ib4]
```
create `MacvlanNetwork`
```
apiVersion: mellanox.com/v1alpha1
kind: MacvlanNetwork
metadata:
  name: rdma-net-ipam-ib1
spec:
  ipam: |
    {
      "type": "whereabouts",
      "range": "10.10.0.0/24",
      "gateway": "10.10.0.1"
    }
  master: ib1
  mode: bridge
  mtu: 1500
  networkNamespace: default
```

create `pod`
```
apiVersion: v1
kind: Pod
metadata:
  name: mofed-test-pod1
  annotations:
    k8s.v1.cni.cncf.io/networks: rdma-net-ipam-ib1
spec:
  nodeName: dixi-8ib-05
  restartPolicy: OnFailure
  containers:
  - image: 172.16.16.66/laiye-foundry/mofed:23.10-1.1.9.0-ubuntu20.04-amd64
    name: mofed-test-ctr
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      limits:
        rdma/mlx5_1: 1
      requests:
        rdma/mlx5_1: 1
```
The error message is as follows：
kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "788de7e085b7b935f160ffeaab972ec071b71febc3f686a5b9936c9b58888bf4" network for pod "mofed-test-pod1": networkPlugin cni failed to set up pod "mofed-test-pod1_default" network: [default/mofed-test-pod1/:rdma-net-ipam-ib1]: error adding container to network "rdma-net-ipam-ib1": failed to create macvlan: invalid argument
