### ISSUE TITLE
Worker Nodes are Drained When Restarting `mofed-ubuntu20.04-ds` Pod

### ISSUE THREAD

**Issue by koh-hr** [Mellanox/network-operator#1084]
I encountered an issue while deploying NVIDIA Network Operator v24.1.0 in the following environment:

- **Host OS**: Ubuntu 20.04 (bare-metal)
- **Kubernetes Version**: v1.27
- **Cluster**: 3 worker nodes

One of the worker nodes failed to start the `mofed-ubuntu20.04-ds` pod. When I checked the logs, I found the following:

```bash
$ kubectl logs -n nvidia-network-operator mofed-ubuntu20.04-ds-z7mfb
Defaulted container "mofed-container" out of: mofed-container, network-operator-init-container (init)
[26-Sep-24_05:02:12] NVIDIA driver container exec start
[26-Sep-24_05:02:12] OS is Ubuntu
[26-Sep-24_05:02:12] [os-release]: NAME="Ubuntu" VERSION="20.04.6 LTS (Focal Fossa)" ID=ubuntu ID_LIKE=debian PRETTY_NAME="Ubuntu 20.04.6 LTS" VERSION_ID="20.04"
[26-Sep-24_05:02:12] [uname -a]: Linux worker04 5.4.0-196-generic #216-Ubuntu SMP Thu Aug 29 13:26:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
[26-Sep-24_05:02:12] Storage modules are loaded for current driver, terminating prior driver reload failure due to UNLOAD_STORAGE_MODULES not set to "true"
```

Based on the log, I set the `UNLOAD_STORAGE_MODULES` environment variable to `true` and restarted the DaemonSet:

```bash
$ kubectl edit ds -n nvidia-network-operator mofed-ubuntu20.04-ds
$ kubectl rollout restart ds -n nvidia-network-operator mofed-ubuntu20.04-ds
```

Here is the updated environment configuration for the DaemonSet:

```yaml
      containers:
      - env:
        - name: CREATE_IFNAMES_UDEV
          value: "true"
        - name: UNLOAD_STORAGE_MODULES
          value: "true"
```

**Issue:**

After this change, the pod did not restart as expected, and instead, the worker nodes were drained one by one. I manually deleted the pod, and it started successfully. 

Is this worker drain behavior expected when `UNLOAD_STORAGE_MODULES` is set to `true`? Why does the DaemonSet not restart the pods properly, and why are the workers drained in this scenario?

**Comment by rollandf** [comment]
Hi, can you share the `NicClusterPolicy` used?
If you specified an `upgradePolicy` to the `ofedDriver` section, it can explain the behavior.
With `upgradepolicy`, any change in the `ofedDriver` section will trigger a drain and cordon of the node, and only then the driver pod will be automatically deleted and restarted.

**Comment by koh-hr** [comment]
@rollandf 
Thank you for your response.

Here is the NicClusterPolicy configuration I am using:
```
  ofedDriver:
    image: doca-driver
    imagePullSecrets: []
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 30
    repository: nvcr.io/nvidia/mellanox
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 20
    terminationGracePeriodSeconds: 300
    upgradePolicy:
      autoUpgrade: true
      drain:
        deleteEmptyDir: true
        enable: true
        force: true
        podSelector: ""
        timeoutSeconds: 300
      maxParallelUpgrades: 1
      safeLoad: false
    version: 24.01-0.3.3.1.3
```
I noticed that I have the upgradePolicy section defined with autoUpgrade set to true, and the drain settings are enabled.

Is it correct to assume that the drain was triggered by this policy when I edited and restarted the mofed-ubuntu20.04-ds DaemonSet?
