### ISSUE TITLE
Unable to get HostDeviceNetwork CNI attached to pod in OCP, missing option in NetworkAttachmentDefinition

### ISSUE THREAD

**Issue by whowutwut** [Mellanox/network-operator#1382]
I'm running the v25.1.0 network operator on OpenShift 4.16 and trying to get the `HostDeviceNetwork` CRD working.  
I'm running a Mellanox CX-6 adapter with a port set to Ethernet mode to test RoCE. 

I am hitting the following error when trying to create a sample pod that is referencing the cni `hostdevicenetwork`. 

`error adding container to network "hostdevicenetwork": specify either "device", "hwaddr", "kernelpath" or "pciBusID"`

Here's the full error on the event on the pod:
```
Warning  FailedCreatePodSandBox  4s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_hostnetpod_default_2673e76f-73da-412d-b057-9172b3a84328_0(e371208b593005941dfea2a77ca7e9f3759c3f0b74d06eba4d0626ea2fc2e068): error adding pod default_hostnetpod to CNI network "multus-cni-network": plugin type="multus-shim" name="multus-cni-network" failed (add): CmdAdd (shim): CNI request failed with status 400: 'ContainerID:"e371208b593005941dfea2a77ca7e9f3759c3f0b74d06eba4d0626ea2fc2e068" Netns:"/var/run/netns/e489f121-12ac-4ca0-8986-e3b14936e2be" IfName:"eth0" Args:"IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=hostnetpod;K8S_POD_INFRA_CONTAINER_ID=e371208b593005941dfea2a77ca7e9f3759c3f0b74d06eba4d0626ea2fc2e068;K8S_POD_UID=2673e76f-73da-412d-b057-9172b3a84328" Path:"" ERRORED: error configuring pod [default/hostnetpod] networking: [default/hostnetpod/2673e76f-73da-412d-b057-9172b3a84328:hostdevicenetwork]: error adding container to network "hostdevicenetwork": specify either "device", "hwaddr", "kernelpath" or "pciBusID"
': StdinData: {"binDir":"/var/lib/cni/bin","clusterNetwork":"/host/run/multus/cni/net.d/10-ovn-kubernetes.conf","cniVersion":"0.3.1","daemonSocketDir":"/run/multus/socket","globalNamespaces":"default,openshift-multus,openshift-sriov-network-operator","logLevel":"verbose","logToStderr":true,"name":"multus-cni-network","namespaceIsolation":true,"type":"multus-shim"}
```

My `HostDeviceNetwork` CR looks like this:

```yaml
kind: HostDeviceNetwork
apiVersion: mellanox.com/v1alpha1
metadata:
  name: hostdevicenetwork
spec:
  ipam: |
    {
      "type": "whereabouts",
      "range": "192.168.1.0/24",
    }
  networkNamespace: default
  resourceName: rdma_ens5f1np1
```

and my `NicClusterPolicy` looks like this:

```yaml
kind: NicClusterPolicy
apiVersion: mellanox.com/v1alpha1
metadata:
  name: nic-cluster-policy
spec:
  rdmaSharedDevicePlugin:
    config: |
      {
        "configList": [
          {
            "resourceName": "rdma_ens5f1np1",
            "rdmaHcaMax": 63,
            "selectors": {
              "vendors": ["15b3"],
              "ifNames": ["ens5f1np1"]
            }
          }
        ]
      }
    image: k8s-rdma-shared-dev-plugin
    repository: ghcr.io/mellanox
    version: 'sha256:9f468fdc4449e65e4772575f83aa85840a00f97165f9a00ba34695c91d610fbd'
```

Here's the sample pod: 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: hostnetpod
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: hostdevicenetwork
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: registry.access.redhat.com/ubi9/ubi:9.4-1214.1726694543
    resources:
      limits:
        rdma/rdma_ens5f1np1: 1
      requests:
        rdma/rdma_ens5f1np1: 1
```

The network attachment definition that is generated by the NVIDIA network operator looks like this: 

```yaml
$ oc get network-attachment-definition  -n default hostdevicenetwork -oyaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: nvidia.com/rdma_ens5f1np1
    nvidia.network-operator.revision: "3746376904"
  creationTimestamp: "2025-03-19T13:28:24Z"
  generation: 1
  labels:
    nvidia.network-operator.state: state-host-device-network
  name: hostdevicenetwork
  namespace: default
  ownerReferences:
  - apiVersion: mellanox.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: HostDeviceNetwork
    name: hostdevicenetwork
    uid: 55e7f688-3126-4e82-85c6-b47ad195fe9b
  resourceVersion: "182089955"
  uid: 0b2c33bb-5bdc-42ae-a600-c1777094ca30
spec:
  config: |-
    { "cniVersion":"0.3.1", "name":"hostdevicenetwork", "type":"host-device", "ipam":{ "type": "whereabouts", "range": "192.168.1.0/24" }
    }
```

I was able to get this working by manually creating a **network-attachment-definition** the looks like the following, where I do specify a device. 

```yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ens5f1np1-roce-host-net
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "ens5f1np1-roce-host-net",
      "type": "host-device",
      "device": "ens5f1np1", <----------------- this device.
      "ipam": {
        "type": "static"
      }
    }
```

This seems consistent with the error message coming out.  

Am I doing something wrong here? Or Is there some option that I can pass into `HostNetworkDevice` CR that allows the device field to get injected into the NAD config?
