### ISSUE TITLE
Add tolerations values for all DaemonSets?

### ISSUE THREAD

**Issue by esigler** [Mellanox/network-operator#302]
Howdy!  Would it be possible to have a "add this toleration to all daemonsets" value that could be applied?  GPU Operator provides such a value ([relevant commit](https://github.com/NVIDIA/gpu-operator/commit/4e4fd43aba76af241d6a24fc1e865b7327c7ba36#diff-634d1afac63d5d768c5ce2a20a947dc0842a3480923500e36c0d6da8dd220e84R312)):

```
daemonsets:
  priorityClassName: system-node-critical
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
```

This would be valuable as we use taints heavily in our cluster "pre flight" node setup, and would like to ensure the Network Operator pods always have proper tolerations.  If this is an acceptable feature, I'd be happy to try creating a pull request to add it?
