### ISSUE TITLE
[QUESTION] difference of  rdma device plugin setting with redhat document

### ISSUE THREAD

**Issue by JuHyung-Son** [Mellanox/network-operator#416]
In network operator defualt helm values, rdma device plugin resource setting is as below.
```
rdmaSharedDevicePlugin:
  deploy: true
  image: k8s-rdma-shared-dev-plugin
  repository: nvcr.io/nvidia/cloud-native
  version: v1.3.2
  # imagePullSecrets: []
  # The following defines the RDMA resources in the cluster
  # it must be provided by the user when deploying the chart
  # each entry in the resources element will create a resource with the provided <name> and list of devices
  # example:
  resources:
    - name: rdma_shared_device_a
      vendors: [15b3]
```

and i have 3 ib nic like below.
```
show_gids
DEV	PORT	INDEX	GID					IPv4  		VER	DEV
---	----	-----	---					------------  	---	---
mlx5_0	1	0	fe80:0000:0000:0000:1070:fd03:0099:9816			v1	
mlx5_1	1	0	fe80:0000:0000:0000:08c0:eb03:0058:026a			v1	
mlx5_2	1	0	fe80:0000:0000:0000:1070:fd03:0099:9852			v1	
n_gids_found=3
```

but in redhat dgx document, they install rdma device plugin as below.
not using `vendors`, using devices and assign each device.

```
config.json: |
 {
 "configList": [{
 "resourceName": "shared_ib0",
 "rdmaHcaMax": 100,
 "devices": ["ib0"]
 },
 {
 "resourceName": "shared_ib1",
 "rdmaHcaMax": 100,
 "devices": ["ib1"]
 },
 {
 "resourceName": "shared_ib2",
 "rdmaHcaMax": 100,
 "devices": ["ib2"]
 },
 {
 "resourceName": "shared_ib3",
 "rdmaHcaMax": 100,
 "devices": ["ib3"]
 }
 ]
 }
```

so i wonder if i have more than 2 ib nics, should I install rdma device plugin like redhat??
