### ISSUE TITLE
NicClusterPolicy generated by Helm chart is not valid

### ISSUE THREAD

**Issue by mkjpryor** [Mellanox/network-operator#452]
**What happened**:

For certain combinations of values, the network-operator Helm chart produces a `NicClusterPolicy` that does not validate against the schema from the CRD. Helm itself and `kubectl apply` seem to be happy, but server-side apply fails.

This means that tools that use server-side apply, such as Argo CD in certain configurations, cannot write the `NicClusterPolicy`.

In particular, values that should be either rendered as empty lists or not rendered at all are rendered as `null`.

**What you expected to happen**:

The chart to produce a valid `NicClusterPolicy`.

**How to reproduce it (as minimally and precisely as possible)**:

```sh
$ helm template mellanox-network-operator network-operator --repo https://mellanox.github.io/network-operator --version 1.4.0 -f values-test.yaml | kubectl apply --server-side=true -f -

serviceaccount/mellanox-network-operator serverside-applied
clusterrole.rbac.authorization.k8s.io/mellanox-network-operator serverside-applied
clusterrolebinding.rbac.authorization.k8s.io/mellanox-network-operator serverside-applied
role.rbac.authorization.k8s.io/mellanox-network-operator serverside-applied
rolebinding.rbac.authorization.k8s.io/mellanox-network-operator serverside-applied
deployment.apps/mellanox-network-operator serverside-applied
pod/mellanox-network-operator-dev-plugin-test serverside-applied
The NicClusterPolicy "nic-cluster-policy" is invalid: 
* spec.ofedDriver.imagePullSecrets: Invalid value: "null": spec.ofedDriver.imagePullSecrets in body must be of type array: "null"
* spec.ofedDriver.upgradePolicy.drain.podSelector: Invalid value: "null": spec.ofedDriver.upgradePolicy.drain.podSelector in body must be of type string: "null"
* spec.rdmaSharedDevicePlugin.imagePullSecrets: Invalid value: "null": spec.rdmaSharedDevicePlugin.imagePullSecrets in body must be of type array: "null"
```

```yaml
# values-test.yaml

operator:
  repository: nvcr.io/nvidia/cloud-native
# Use the shared NFD
nfd:
  enabled: false
# Deploy the default NICClusterPolicy
deployCR: true
# Deploy the OFED driver onto nodes with a suitable NIC
ofedDriver:
  deploy: true
  repository: nvcr.io/nvidia/mellanox
  # OFED takes ages to deploy on low-resource nodes
  # The startup probe has a fixed failure threshold of 60
  # So in order to give the drivers up to one hour to install, we use a period
  # of 60 seconds for the startup probe
  startupProbe:
    initialDelaySeconds: 60
    periodSeconds: 60
# Deploy the RDMA shared device plugin to allow pods to access the RDMA device
rdmaSharedDevicePlugin:
  deploy: true
  repository: nvcr.io/nvidia/cloud-native
# Disable all other features for now
ibKubernetes:
  deploy: false
  repository: ghcr.io/mellanox
nvPeerDriver:
  deploy: false
  repository: docker.io/mellanox
sriovNetworkOperator:
  enabled: false
sriovDevicePlugin:
  deploy: false
  repository: ghcr.io/k8snetworkplumbingwg
secondaryNetwork:
  deploy: false
  cniPlugins:
    repository: ghcr.io/k8snetworkplumbingwg
  multus:
    repository: ghcr.io/k8snetworkplumbingwg
  ipoib:
    repository: nvcr.io/nvidia/cloud-native
  ipamPlugin:
    repository: ghcr.io/k8snetworkplumbingwg
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.25
- Hardware configuration:
  - Network adapter model and firmware version:
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04
- Kernel (e.g. `uname -a`):
- Others:
