### ISSUE TITLE
Memory limit for whereabouts Pod is too strict

### ISSUE THREAD

**Issue by ykulazhenkov** [Mellanox/network-operator#517]
/manifests/stage-whereabouts-cni/0050-whereabouts-ds.yaml has to strict limits for whereabouts Pod

```
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
```

This may cause whereabouts Pod to fail with "cgroup out of memory" on some environments.

In the whereabouts repo they have larger limits 
https://github.com/k8snetworkplumbingwg/whereabouts/blob/515fbb9fe9db8b056bc48f6537f56446513028aa/doc/crds/daemonset-install.yaml#L120

Proposed fix: remove memory limits for whereabouts Pod, we don't have memory limits for other controllers which are deployed by the net op.
