### ISSUE TITLE
network-operator can't achieve stable state when NVIDIA IPAM deployment is enabled

### ISSUE THREAD

**Issue by ykulazhenkov** [Mellanox/network-operator#548]
**What happened**:
network-operator continues to execute sync loop indefinitely if NVIDIA IPAM deployment is enabled

**What you expected to happen**:
network-operator should be in stable state

**How to reproduce it (as minimally and precisely as possible)**:
deploy network-operator with NVIDIA IPAM

**Anything else we need to know?**:
In each sync loop Generation of the `nv-ipam-controller` Deployment is updated, need to check why

**Logs**:
- NicClusterPolicy CR spec and state: 
```
apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: nic-cluster-policy
spec:
  secondaryNetwork:
    cniPlugins:
      image: plugins
      repository: ghcr.io/k8snetworkplumbingwg
      version: v1.2.0-amd64
    multus:
      image: multus-cni
      repository: ghcr.io/k8snetworkplumbingwg
      version: v3.9.3
      config: ''
  nvIpam:
    image: nvidia-k8s-ipam
    repository: ghcr.io/mellanox
    version: v0.0.2
    config: '{
      "pools":  {
        "my-pool": {"subnet": "192.168.0.0/16", "perNodeBlockSize": 100, "gateway": "192.168.0.1"}
      }
    }'
```

```
nic-cluster-policy   ready    2023-06-06T07:33:56Z
```
- Network Operator version: master(e1267e871cdf0241ba696b7a0ebfd3de1fe95455)
