### ISSUE TITLE
Network Operator docs: Wrong config for deployment scenario "Network Operator Deployment with NVIDIA-IPAM"

### ISSUE THREAD

**Issue by gseidlerhpe** [Mellanox/network-operator#889]
**What happened**:
Followed documentation to deploy Network Operator Deployment with NVIDIA-IPAM:
https://docs.nvidia.com/networking/display/kubernetes2310/network+operator#src-144713486_NetworkOperator-NetworkOperatorDeploymentwithNVIDIA-IPAM

NVIDIA-IPAM CRD  was not deployed. Could not deploy the NV-IPAM IPPool,.

**What you expected to happen**:
NVIDIA-IPAM CRD and CNI Plugin is deployed and configured.

**How to reproduce it (as minimally and precisely as possible)**:
Follow doc example.

**Anything else we need to know?**:
The documented values.yaml is wrong.
The entry nvIpam must not be under secondaryNetwork. 
```
nfd:
  enabled: false
  deployNodeFeatureRules: true

operator:
  tolerations: []
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10
          preference:
            matchExpressions:
              - key: "node-role.kubernetes.io/worker"
                operator: In
                values: [""]
        - weight: 1
          preference:
            matchExpressions:
              - key: "hpe.com/dataplatform"
                operator: NotIn
                values: ["true"]
        - weight: 1
          preference:
            matchExpressions:
              - key: "node-role.kubernetes.io/control-plane"
                operator: In
                values: [ "" ]

sriovNetworkOperator:
  enabled: false

# NicClusterPolicy CR values:
deployCR: true

nvPeerDriver:
  deploy: false

rdmaSharedDevicePlugin:
  deploy: true
  resources:
    - name: rdma_shared_device_a
      ifNames: [ens2f0, ens5f0]

secondaryNetwork:
  deploy: true
  multus:
    deploy: true
  cniPlugins:
    deploy: true
  ipamPlugin:
    deploy: false

nvIpam:
  deploy: true
 
sriovDevicePlugin:
  deploy: false

ofedDriver:
  deploy: true
  repoConfig:
    name: repo-config
  env:
  - name: HTTPS_PROXY
    value: http://proxy-de.its.hpecorp.net:443
  - name: HTTP_PROXY
    value: http://proxy-de.its.hpecorp.net:443
  - name: https_proxy
    value: http://proxy-de.its.hpecorp.net:443
  - name: http_proxy
    value: http://proxy-de.its.hpecorp.net:443

nicFeatureDiscovery:
  deploy: true

```

**Logs**:
- NicClusterPolicy CR spec and state:
- Output of: `kubectl -n nvidia-network-operator get -A`:
- Network Operator version:
- Logs of Network Operator controller:
- Logs of the various Pods in `nvidia-network-operator` namespace:
- Helm Configuration (if applicable):
- Kubernetes' nodes information (labels, annotations and status): `kubectl get node -o yaml`:

**Environment**:
- Kubernetes version (use `kubectl version`): 
- Hardware configuration:
  - Network adapter model and firmware version:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:
