### ISSUE TITLE
RDMA networking failed

### ISSUE THREAD

**Issue by asdfry** [Mellanox/network-operator#953]
Hello,

I have installed the network-operator based on the following values.yaml.
```
deployCR: true
rdmaSharedDevicePlugin:
  deploy: true
  resources:
    - name: rdma_shared_device_a
      vendors: ["15b3"]
      deviceIDs: ["1017", "1021", "101b"]
secondaryNetwork:
  deploy: true
  multus:
    deploy: true
  cniPlugins:
    deploy: true
  ipamPlugin:
    deploy: true
```

I'm trying to run two pods with RDMA devices and test RDMA communication using ib_send_bw, but I'm encountering this error. (The test works fine without the -R option)
![image](https://github.com/Mellanox/network-operator/assets/39879672/7b6995bf-fd26-4e60-b2e5-2c309b613cc0)

Is there anything else I need to do besides installing the Network Operator?
I referred to [this link](https://docs.nvidia.com/networking/display/cokan10/network+operator#src-39285883_NetworkOperator-NetworkOperatorDeploymentwithaSecondaryNetwork), but it only provides an example for values.yaml and nothing else.

Here is yaml that creating two pod.
```
apiVersion: v1
kind: Pod
metadata:
  name: rdma-test-node7
  namespace: jsh
spec:
  containers:
  - name: app
    image: asdfry/train-llm:20240411
    command: ["/bin/bash", "-c"]
    args: ["sleep infinity"]
    resources:
      limits:
        ten1010.io/gpu-nvidia-l40: "4"
        rdma/rdma_shared_device_a: "1"
      requests:
        ten1010.io/gpu-nvidia-l40: "4"
        rdma/rdma_shared_device_a: "1"
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
---
apiVersion: v1
kind: Pod
metadata:
  name: rdma-test-node9
  namespace: jsh
spec:
  containers:
  - name: app
    image: asdfry/train-llm:20240411
    command: ["/bin/bash", "-c"]
    args: ["sleep infinity"]
    resources:
      limits:
        ten1010.io/gpu-nvidia-l4: "4"
        rdma/rdma_shared_device_a: "1"
      requests:
        ten1010.io/gpu-nvidia-l4: "4"
        rdma/rdma_shared_device_a: "1"
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
```
