### ISSUE TITLE
Incorrect deviceClassWhitelist configuration is provided

### ISSUE THREAD

**Issue by fprzewozny** [Mellanox/network-operator#957]
Hey, 
Going through live system configuration I have noticed, that `network-operator-node-feature-discovery-worker-conf` contains incorrect device class whitelist:
```
apiVersion: v1
data:
 nfd-worker.conf: |-
  sources:
   pci:
    deviceClassWhitelist:
    - "0300"
    - "0302"
    deviceLabelFields:
    - vendor
kind: ConfigMap
```
According to [PCI-SIG specifications](https://pcisig.com/sites/default/files/files/PCI_Code-ID_r_1_11__v24_Jan_2019.pdf), base class `03` is `Display controller`, `00` subclass of `03` class is `VGA-compatible controller`, and `02` subclass of `03` class is `3D controller `.  So provided configuration with operator translates to:
```
    deviceClassWhitelist:
    - "0300"  # VGA-compatible controller
    - "0302"  # 3D controller
```
With such filters it seems like `network-operator-node-feature-discovery` is configured to gather GPU data (that should be done with f.e. https://github.com/NVIDIA/gpu-feature-discovery, which have similar configuration issue I will link here once it's created). In my opinion, `deviceClassWhitelist` should contain entries only from `02` classes (Network).

In code repo it can be found here: https://github.com/Mellanox/network-operator/blob/17d04f562e4edc81b21b965e87064638bef78c91/hack/templates/values/values.template#L49 and https://github.com/Mellanox/network-operator/blob/17d04f562e4edc81b21b965e87064638bef78c91/deployment/network-operator/values.yaml#L49

Thank you,
Franciszek
